fix: use git diff to verify v* tag and main's head point to same commit

diff --git a/.github/workflows/test_release_me_gitops_phase_1.yml b/.github/workflows/test_release_me_gitops_phase_1.yml
--- a/.github/workflows/test_release_me_gitops_phase_1.yml
+++ b/.github/workflows/test_release_me_gitops_phase_1.yml
@@ -319,27 +319,42 @@ jobs:
 
           done
 
-      - run: git tag -l
-      - run: sleep 10
-      - run: git tag -l
-
       # THEN Assert that after Code merge to Main, a v* Tag was pushed to main
-      - name: "Check if v* Git Tag was pushed to '${{ env.MAIN_BR }}' branch, after Code merge to ${{ env.MAIN_BR }} branch"
-        uses: rickstaa/action-contains-tag@v1
-        id: main_contains_tag
-        with:
-          reference: ${{ env.MAIN_BR }}
-          tag: "${{ env.EXPECTED_PROD_TAG }}"
-
       - name: Assert that the ${{ env.EXPECTED_PROD_TAG }} Tag was pushed on '${{ env.MAIN_BR }}' Branch
+        env:
+          # times in seconds
+          TIMEOUT_LIMIT: 30
+          POLL_FREQUENCY: 4
+        # We verify the diff between the Expected Prod tag and main head is empty
+        working-directory: ${{ env._GO_DIR }}
         run: |
-          if steps.main_contains_tag.outputs.contains_tag == 'true'; then
-            echo "**Asserted PROD Tag '${{ env.EXPECTED_PROD_TAG }}' was pushed** on the ${{ env.MAIN_BR }} Branch" >> $GITHUB_STEP_SUMMARY
-          else
-            echo "[Assertion Error] PROD Tag was not pushed on the ${{ env.MAIN_BR }} Branch"
-            echo "Exiting with error..."
-            exit 1
-          fi
+          git fetch
+          git checkout main
+          git pull origin main
+          start_time=$(date +%s)
+
+          diffs=$(git diff --name-only "${{ env.EXPECTED_PROD_TAG }}" "${{ env.MAIN_BR }}")
+
+          while true; do
+            if [ -z "$diffs" ]; then
+              echo "[INFO] Asserted PROD Tag '${{ env.EXPECTED_PROD_TAG }}' was pointed to same commit as head of ${{ env.MAIN_BR }} Branch"
+              break
+            else
+              current_time=$(date +%s)
+              elapsed_time=$(($current_time - $start_time))
+
+              if [ $elapsed_time -ge ${{ env.TIMEOUT_LIMIT }} ]; then
+                echo "[Assertion Error] PROD Tag was not pushed on the ${{ env.MAIN_BR }} Branch"
+                echo "Exiting with error..."
+                exit 1
+              fi
+            fi
+
+            # Sleep for ${{ env.POLL_FREQUENCY }} seconds
+            sleep ${{ env.POLL_FREQUENCY }}
+            git fetch
+            diffs=$(git diff --name-only "${{ env.EXPECTED_PROD_TAG }}" "${{ env.MAIN_BR }}")
+          done
 
       # in the future we may assert that Github Release was also made from that tag (which is now on main branch)
 
@@ -763,3 +778,21 @@ jobs:
         #     # Sleep for ${{ env.POLL_FREQUENCY }} seconds
         #     sleep ${{ env.POLL_FREQUENCY }}
         #   done
+
+      # # THEN Assert that after Code merge to Main, a v* Tag was pushed to main
+      # - name: "Check if v* Git Tag was pushed to '${{ env.MAIN_BR }}' branch, after Code merge to ${{ env.MAIN_BR }} branch"
+      #   uses: rickstaa/action-contains-tag@v1
+      #   id: main_contains_tag
+      #   with:
+      #     reference: ${{ env.MAIN_BR }}
+      #     tag: "${{ env.EXPECTED_PROD_TAG }}"
+
+      # - name: Assert that the ${{ env.EXPECTED_PROD_TAG }} Tag was pushed on '${{ env.MAIN_BR }}' Branch
+      #   run: |
+      #     if steps.main_contains_tag.outputs.contains_tag == 'true'; then
+      #       echo "**Asserted PROD Tag '${{ env.EXPECTED_PROD_TAG }}' was pushed** on the ${{ env.MAIN_BR }} Branch" >> $GITHUB_STEP_SUMMARY
+      #     else
+      #       echo "[Assertion Error] PROD Tag was not pushed on the ${{ env.MAIN_BR }} Branch"
+      #       echo "Exiting with error..."
+      #       exit 1
+      #     fi
