feat: print more info to Job Console, for visual sanity check

diff --git a/.github/workflows/test_release_me_gitops_phase_1.yml b/.github/workflows/test_release_me_gitops_phase_1.yml
--- a/.github/workflows/test_release_me_gitops_phase_1.yml
+++ b/.github/workflows/test_release_me_gitops_phase_1.yml
@@ -36,14 +36,21 @@ jobs:
   setup:
     runs-on: ubuntu-latest
     env:
+      # Release branch, we assume client repo adopts/uses
+      RELEASE_BR: release
       # GIVEN / Internal Environment Variables for DRY
       _USER_BR: "user-branch-${{ github.run_id }}"
       _GO_OWNER: 'boromir674'
       _GO_REPO_NAME: 'gitops-automation'
       _GO_REPO: 'boromir674/gitops-automation'
       _GO_DIR: "go-repo"
+      # TEST CASE 1 - DATA
       # CONSTANT Env Var for `auto-prod` tag, of `release-me` process phase 2 
       TAG_PHASE_2: "auto-prod-1.0.0"
+      EXPECTED_RC_TAG: "v1.0.0-rc"
+      # TEST CASE 2 - DATA
+      # TAG_PHASE_2: "auto-prod-1.3.0-dev"
+      # EXPECTED_RC_TAG: "v1.3.0-dev"
     steps:
 
       # GIVEN a Client Repo with 'main' and 'release' branches
@@ -62,6 +69,8 @@ jobs:
 
       - name: Make dummy changes on local User Branch '${_USER_BR}'
         working-directory: ${{ env._GO_DIR }}
+        env:
+          TOPICAL_BRANCH_CHANGES_FILE: "changes-from-topical-branch.txt"
         # env:
         #   GITHUB_TOKEN: ${{ secrets.CICD_TEST_GH_TOKEN }}
         run: |
@@ -69,8 +78,8 @@ jobs:
           git config --local user.email "boromir674@hotmail.com"
 
           git checkout -b ${_USER_BR}
-          echo "User Branch" > "${_USER_BR}.txt"
-          git add "${_USER_BR}.txt"
+          echo "User Branch '${_USER_BR}'" > "${TOPICAL_BRANCH_CHANGES_FILE}"
+          git add "${TOPICAL_BRANCH_CHANGES_FILE}"
 
           git commit -m "auto-commit: write (literally) the User's Branch name '${_USER_BR}' to a file"
 
@@ -117,13 +126,13 @@ jobs:
         env:
           # pass in env vars required for test case
           GO_INCOMING_BRANCH: ${{ env._USER_BR }}
-          GO_RELEASE_BRANCH: 'release'
+          GO_RELEASE_BRANCH: ${{ env.RELEASE_BR }}
           # if test code has auth issues pass in another token:
           # GITHUB_TOKEN: ${{ secrets.SOME_AUTHORIZED_GH_TOKEN }}
           GITHUB_TOKEN: ${{ secrets.READ_PR_GITOPS_AUTOMATION }}
         run: tox -vv -e test -- -n auto -vvs -k 'test_pr_to_release_opened_n_closed or test_pr_to_main_opened' --run-gitops
 
-      ### TEST PHASE 2 ###
+      #### TEST PHASE 2 ####
 
       # [OPT] assert the expected labels has been put to PR -> 'release'
 
@@ -137,14 +146,17 @@ jobs:
           set-safe-directory: ''  # `git config --global --add safe.directory <path>`
           token: ${{ secrets.PUSH_TO_GITOPS_AUTOMATION }}
 
-      # AND GIVEN we emulate some plausible git steps, like Changelog.md update and Sem Ver bump
-      - name: Sync release branch
+      # AND GIVEN we emulate some plausible git steps on Release branch
+      # EG: Changelog.md update and Sem Ver bump
+      - name: Sync '${{ env.RELEASE_BR }}' branch
         working-directory: ${{ env._GO_DIR }}
+        env:
+          release: ${{ env.RELEASE_BR }}
         run: |
           git fetch
-          git branch --track release origin/release || echo "Found local Branch 'release'"
-          git checkout release
-          git pull origin release
+          git branch --track $release "origin/${release}" || echo "Found local Branch '${release}'"
+          git checkout "${release}"
+          git pull origin "${release}"
 
       # Sem Ver Bump in sources is not relevant for the gitops-automation project
 
@@ -163,7 +175,7 @@ jobs:
           git config user.name "Konstantinos Lampridis"
           git config user.email "boromir674@hotmail.com"
           git commit -m "auto-commit: update CHANGELOG.md with dummy Release entry"
-          git push origin release
+          git push origin ${{ env.RELEASE_BR }}
 
       # WHEN we trigger the 2nd `release-me` Phase of the Git Ops Process
       - name: "Push Git Tag '${{ env.TAG_PHASE_2 }}'"
@@ -176,32 +188,27 @@ jobs:
           git push origin "${{ env.TAG_PHASE_2 }}"
 
       # THEN Assert that an RC tag was pushed on Release Branch
-      - name: Assert that an RC tag was pushed on Release Branch
+      - name: Assert that the RC tag '${{ env.EXPECTED_RC_TAG }}' was pushed on '${{ env.RELEASE_BR }}' Branch
         env:
-          GO_INCOMING_BRANCH: ${{ env._USER_BR }}
-          GO_RELEASE_BRANCH: 'release'
           # if test code has auth issues pass in another token:
           # GITHUB_TOKEN: ${{ secrets.READ_PR_GITOPS_AUTOMATION }}
           # try the github provided token
           token: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          repo="${_GO_REPO}"
-          branch="release"
-          tag="${{ env.TAG_PHASE_2 }}"
           start_time=$(date +%s)
 
-          # Get the commit SHA of the head of the release branch
+          # Get the commit SHA of the head of the ${{ env.RELEASE_BR }} branch
           branch_sha=$(curl -s -H "Authorization: token ${token}" \
-            "https://api.github.com/repos/${{ env._GO_REPO }}/git/refs/heads/$branch" | jq -r '.object.sha')
+            "https://api.github.com/repos/${{ env._GO_REPO }}/git/refs/heads/${{ env.RELEASE_BR }}" | jq -r '.object.sha')
           while true; do
 
             # Get the list of tags in the repository
             tag_sha=$(curl -s -H "Authorization: token ${token}" \
-              "https://api.github.com/repos/${{ env._GO_REPO }}/git/refs/tags/$tag" | jq -r '.object.sha')
+              "https://api.github.com/repos/${{ env._GO_REPO }}/git/refs/tags/${{ env.EXPECTED_RC_TAG }}" | jq -r '.object.sha')
 
             # Compare the commit SHA of the tag and the release branch
             if [ "$branch_sha" = "$tag_sha" ]; then
-              echo "[INFO] Asserted RC Tag was pushed on the Release Branch"
+              echo "[INFO] Asserted RC Tag '${{ env.EXPECTED_RC_TAG }}' was pushed on the ${{ env.RELEASE_BR }} Branch"
               echo PR_RELEASE_TIMESTAMP=$(date +%s) >> $GITHUB_ENV
               break
             else
@@ -209,7 +216,7 @@ jobs:
               elapsed_time=$(($current_time - $start_time))
 
               if [ $elapsed_time -ge 20 ]; then
-                echo "[Assertion Error] RC Tag was not pushed on the Release Branch"
+                echo "[Assertion Error] RC Tag was not pushed on the ${{ env.RELEASE_BR }} Branch"
                 echo "Exiting with error..."
                 exit 1
               fi
