feat: automatically test that release-me and auto-prod-* tags are Cleaned Up

diff --git a/.github/workflows/test_release_me_gitops_phase_1.yml b/.github/workflows/test_release_me_gitops_phase_1.yml
--- a/.github/workflows/test_release_me_gitops_phase_1.yml
+++ b/.github/workflows/test_release_me_gitops_phase_1.yml
@@ -358,7 +358,48 @@ jobs:
 
       # in the future we may assert that Github Release was also made from that tag (which is now on main branch)
 
-      # CLEAN UP kind of step
+      # THEN Assert that if Clean-up is Setup, the release-me and all auto-prod-* tags are deleted
+      - name: Assert that Clean-up kicks-in, and deletes the release-me and all auto-prod-* tags
+        env:
+          # times in seconds
+          TIMEOUT_LIMIT: 30
+          POLL_FREQUENCY: 4
+        working-directory: ${{ env._GO_DIR }}
+        run: |
+          start_time=$(date +%s)
+
+          while true; do
+            # ensure no local release-me or auto-prod-* tags exist
+            git tag --delete release-me || true
+            git tag -d $(git tag | grep "auto-prod-")
+            git fetch --tags
+
+            # stop with success if no tags are found
+            release_me_tag=$(git tag --list "release-me")
+            if [ -z "$release_me_tag" ]; then
+              echo "[INFO] Asserted that 'release-me' tag, was Cleaned-Up"
+              auto_prod_tags=$(git tag --list "auto-prod-*")
+              if [ -z "$auto_prod_tags" ]; then
+                echo "[INFO] Asserted that all auto-prod-* tags were Cleaned-Up"
+                break
+              fi
+            fi
+
+            current_time=$(date +%s)
+            elapsed_time=$(($current_time - $start_time))
+
+            if [ $elapsed_time -ge ${{ env.TIMEOUT_LIMIT }} ]; then
+              # stop with error if could not Assert within the time limit
+              echo "[Assertion Error] Not all Git Ops Tags were Cleaned-Up!"
+              echo "Exiting with error.."
+              exit 1
+            fi
+
+            sleep ${{ env.POLL_FREQUENCY }}
+          done
+
+
+      # Test - CLEAN UP kind of step
       - name: Put release branch to same commit as main to avoid future conflicts
         if: always()
         working-directory: ${{ env._GO_DIR }}
