feat: assert Release Me process automatically tags main after PR merge!

diff --git a/.github/workflows/test_release_me_gitops_phase_1.yml b/.github/workflows/test_release_me_gitops_phase_1.yml
--- a/.github/workflows/test_release_me_gitops_phase_1.yml
+++ b/.github/workflows/test_release_me_gitops_phase_1.yml
@@ -50,6 +50,7 @@ jobs:
       # CONSTANT Env Var for `auto-prod` tag, of `release-me` process phase 2 
       TAG_PHASE_2: "auto-prod-1.0.0"
       EXPECTED_RC_TAG: "v1.0.0-rc"
+      EXPECTED_PROD_TAG: "v1.0.0"
       # TEST CASE 2 - DATA
       # TAG_PHASE_2: "auto-prod-1.3.0-dev"
       # EXPECTED_RC_TAG: "v1.3.0-dev"
@@ -240,7 +241,7 @@ jobs:
       # in the future we can assert whether the tag was a DEV Release or a PROD Release
       
 
-      # THEN Assert that exatly one PR to main closed, with code merge, after PR_RELEASE_TIMESTAMP
+      # THEN Assert that exactly one PR to main closed, with code merge, after PR_RELEASE_TIMESTAMP
       - name: Assert that the PR to main closed with code merge
         env:
           token: ${{ secrets.GITHUB_TOKEN }}
@@ -310,10 +311,56 @@ jobs:
 
           done
 
-      # in the future we may assert that Main Br got PROD tag (v1.0.0, v1.2.0-dev, etc)
-      # given the auto-prod-1.0.0 event tag
+      # THEN Assert that after Code merge to Main, a v* Tag was pushed to main
+      - name: Assert that the ${{ env.EXPECTED_PROD_TAG }} Tag was pushed on 'main' Branch
+        env:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          # times in seconds
+          TIME_TO_WAIT: 30
+          POLL_FREQUENCY: 3.5
+        run: |
+          start_time=$(date +%s)
 
-      # and that a Github Release was also made from that tag (which is now on main branch)
+          # DEBUG
+          echo "[DEBUG] SHA of latest commit on 'main' branch, of '${{ env._GO_REPO }}' repo"
+          curl -s -H "Authorization: token ${token}" "https://api.github.com/repos/${{ env._GO_REPO }}/git/refs/heads/main"
+          echo
+
+          # Get the commit SHA of the head of the main branch
+          branch_sha=$(curl -s -H "Authorization: token ${token}" \
+            "https://api.github.com/repos/${{ env._GO_REPO }}/git/refs/heads/main" | jq -r '.object.sha')
+
+          while true; do
+
+            # DEBUG
+            echo "[DEBUG] SHA of '${{ env.TAG_PHASE_2 }}' Tag, of '${{ env._GO_REPO }}' repo"
+            curl -s -H "Authorization: token ${token}" "https://api.github.com/repos/${{ env._GO_REPO }}/git/refs/tags/${{ env.TAG_PHASE_2 }}"
+            echo
+
+            # Get the list of tags in the repository
+            tag_sha=$(curl -s -H "Authorization: token ${token}" \
+              "https://api.github.com/repos/${{ env._GO_REPO }}/git/refs/tags/${{ env.EXPECTED_PROD_TAG }}" | jq -r '.object.sha')
+
+            # Compare the commit SHA of the tag and the release branch
+            if [ "$branch_sha" = "$tag_sha" ]; then
+              echo "[INFO] Asserted PROD Tag '${{ env.EXPECTED_PROD_TAG }}' was pushed on the main Branch"
+              break
+            else
+              current_time=$(date +%s)
+              elapsed_time=$(($current_time - $start_time))
+
+              if [ $elapsed_time -ge ${{ env.TIME_TO_WAIT }} ]; then
+                echo "[Assertion Error] PROD Tag was not pushed on the main Branch"
+                echo "Exiting with error..."
+                exit 1
+              fi
+            fi
+
+            # Sleep for ${{ env.POLL_FREQUENCY }} seconds
+            sleep ${{ env.POLL_FREQUENCY }}
+          done
+
+      # in the future we may assert that Github Release was also made from that tag (which is now on main branch)
 
       # CLEAN UP kind of step
       - name: Put release branch to same commit as main to avoid future conflicts
@@ -350,6 +397,7 @@ jobs:
       # CONSTANT Env Var for `auto-prod` tag, of `release-me` process phase 2 
       TAG_PHASE_2: "auto-prod-1.2.1-dev"
       EXPECTED_RC_TAG: "v1.2.1-dev"
+      EXPECTED_PROD_TAG: "v1.2.1-dev"
     steps:
 
       # GIVEN a Client Repo with 'main' and 'release' branches
@@ -607,12 +655,59 @@ jobs:
 
           done
 
-      # in the future we may assert that Main Br got PROD tag (v1.0.0, v1.2.0-dev, etc)
-      # given the auto-prod-1.0.0 event tag
+      # THEN Assert that after Code merge to Main, a v* Tag was pushed to main
+      - name: Assert that the ${{ env.EXPECTED_PROD_TAG }} Tag was pushed on 'main' Branch
+        env:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          # times in seconds
+          TIME_TO_WAIT: 30
+          POLL_FREQUENCY: 3.5
+        run: |
+          start_time=$(date +%s)
 
-      # and that a Github Release was also made from that tag (which is now on main branch)
+          # DEBUG
+          echo "[DEBUG] SHA of latest commit on 'main' branch, of '${{ env._GO_REPO }}' repo"
+          curl -s -H "Authorization: token ${token}" "https://api.github.com/repos/${{ env._GO_REPO }}/git/refs/heads/main"
+          echo
 
-      # CLEAN UP kind of step
+          # Get the commit SHA of the head of the main branch
+          branch_sha=$(curl -s -H "Authorization: token ${token}" \
+            "https://api.github.com/repos/${{ env._GO_REPO }}/git/refs/heads/main" | jq -r '.object.sha')
+
+          while true; do
+
+            # DEBUG
+            echo "[DEBUG] SHA of '${{ env.EXPECTED_PROD_TAG }}' Tag, of '${{ env._GO_REPO }}' repo"
+            curl -s -H "Authorization: token ${token}" "https://api.github.com/repos/${{ env._GO_REPO }}/git/refs/tags/${{ env.EXPECTED_PROD_TAG }}"
+            echo
+
+            # Look for tag ${{ env.EXPECTED_PROD_TAG }} and extract its SHA, if found
+            tag_sha=$(curl -s -H "Authorization: token ${token}" \
+              "https://api.github.com/repos/${{ env._GO_REPO }}/git/refs/tags/${{ env.EXPECTED_PROD_TAG }}" | jq -r '.object.sha')
+
+            # Compare the commit SHA of the tag and the release branch
+            if [ "$branch_sha" = "$tag_sha" ]; then
+              echo "[INFO] Asserted PROD Tag '${{ env.EXPECTED_PROD_TAG }}' was pushed on the main Branch"
+              break
+            else
+              current_time=$(date +%s)
+              elapsed_time=$(($current_time - $start_time))
+
+              if [ $elapsed_time -ge ${{ env.TIME_TO_WAIT }} ]; then
+                echo "[Assertion Error] PROD Tag was not pushed on the main Branch"
+                echo "Exiting with error..."
+                exit 1
+              fi
+            fi
+
+            # Sleep for ${{ env.POLL_FREQUENCY }} seconds
+            sleep ${{ env.POLL_FREQUENCY }}
+          done
+
+      # in the future we may assert that Github Release was also made from that tag (which is now on main branch)
+
+
+      ## CLEAN UP kind of step ##
       - name: Put release branch to same commit as main to avoid future conflicts
         if: always()
         working-directory: ${{ env._GO_DIR }}
