feat(docker): fail test, in case tes scenario prerequisuites were not met at runtime

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -34,7 +34,16 @@ jobs:
     # ASSERT ALL: needed Job called and passed & this Job exits with 0
       runs-on: ubuntu-latest
       needs: call_docker_job_after_ci_pass
+      if: always()
       steps:
+        - name: "Assert CI Tests passed (or test code is wrong)"
+          run: |
+            if [ ${{ needs.mock_succeeded_ci_test_job.result }} -ne 0 ]; then
+              echo "[ERROR] Test Scenario Incorrect Prerequisites NOT satisfied"
+              echo "[DEBUG] Test assumes succeeded CI Test Job, but our Mock CI Tests failed!"
+              echo "Exiting with 1"
+              exit 1
+            fi
         - run: echo ${{ needs.call_docker_jon.outputs.IMAGE_REF }}
         - run: echo "IMAGE_REF=${{ needs.call_docker_jon.outputs.IMAGE_REF }}" >> $GITHUB_ENV
         - name: Retrieve Layers of ${{ needs.call_docker_jon.outputs.IMAGE_REF }}
