feat: verify RC Tag pushed and PR merged to main, for 'release-me' automated test

diff --git a/.github/workflows/test_release_me_gitops_phase_1.yml b/.github/workflows/test_release_me_gitops_phase_1.yml
--- a/.github/workflows/test_release_me_gitops_phase_1.yml
+++ b/.github/workflows/test_release_me_gitops_phase_1.yml
@@ -26,6 +26,12 @@ on:
 
 # THEN Assert PR opened against 'main' branch
 
+# AND GIVEN we emulate some plausible git steps, like Changelog.md update and Sem Ver bump 
+
+# WHEN we trigger the 2nd `release-me` Phase of the Git Ops Process
+
+# THEN Assert that the PR to main closed with code merge
+
 jobs:
   setup:
     runs-on: ubuntu-latest
@@ -36,6 +42,8 @@ jobs:
       _GO_REPO_NAME: 'gitops-automation'
       _GO_REPO: 'boromir674/gitops-automation'
       _GO_DIR: "go-repo"
+      # CONSTANT Env Var for `auto-prod` tag, of `release-me` process phase 2 
+      TAG_PHASE_2: "auto-prod-1.0.0"
     steps:
 
       # GIVEN a Client Repo with 'main' and 'release' branches
@@ -69,7 +77,6 @@ jobs:
       - name: Push User Branch on '${{ env._GO_REPO }}' repo
         working-directory: ${{ env._GO_DIR }}
         run: git push origin ${_USER_BR}
-
 
       # WHEN a 'board-n-release' event is fired from client repo
       - name: Fire 'board-n-release' git tag event, scoped on '${{ env._GO_REPO }}' repo
@@ -106,7 +113,7 @@ jobs:
       # AND PR to main Opened
       # Assert PR Closed with Merge from ${{ env._USER_BR }} to 'release' branch, on ${{ env._GO_REPO_NAME }} github repo
       # AND PR to main Opened
-      - name: Assert 'relase-me' git ops event 1st phase's state (PR to 'release' closed with merge, PR to 'main' opened) reached
+      - name: Assert 'release-me' git ops event 1st phase's state (PR to 'release' closed with merge, PR to 'main' opened) reached
         env:
           # pass in env vars required for test case
           GO_INCOMING_BRANCH: ${{ env._USER_BR }}
@@ -119,4 +126,138 @@ jobs:
 
       # [OPT] assert the expected labels has been put to PR -> 'release'
 
-      # THEN Assert PR opened against 'main' branch
+      # AND GIVEN we emulate some plausible git steps, like Changelog.md update and Sem Ver bump
+      - name: Sync release branch
+        working-directory: ${{ env._GO_DIR }}
+        run: |
+          git fetch
+          git branch --track release origin/release || echo "Found local Branch 'release'"
+          git checkout release
+          git pull origin release
+      
+      # Sem Ver Bump in sources is not relevant for the gitops-automation project
+
+      # Emulate Changelog.md update
+      - name: "Emulate updating CHANGELOG.md with new Release entry"
+        working-directory: ${{ env._GO_DIR }}
+        run: |
+          echo "## [Unreleased]" > CHANGELOG.md
+          echo "### Added" >> CHANGELOG.md
+          echo "- ${_USER_BR}" >> CHANGELOG.md
+          echo "" >> CHANGELOG.md
+          echo "" >> CHANGELOG.md
+          cat CHANGELOG.md
+
+          git add CHANGELOG.md
+          git commit -m "auto-commit: update CHANGELOG.md with dummy Release entry"
+          git push origin release
+
+      # WHEN we trigger the 2nd `release-me` Phase of the Git Ops Process
+      - name: "Push Git Tag '${{ env.TAG_PHASE_2 }}'"
+        working-directory: ${{ env._GO_DIR }}
+        run: |
+          git tag -d "${{ env.TAG_PHASE_2 }}" || echo "No tag to delete"
+          git push --delete origin "${{ env.TAG_PHASE_2 }}" || echo "No tag to delete"
+
+          git tag "${{ env.TAG_PHASE_2 }}"
+          git push origin "${{ env.TAG_PHASE_2 }}"
+
+      # THEN Assert that an RC tag was pushed on Release Branch
+      - name: Assert that an RC tag was pushed on Release Branch
+        env:
+          GO_INCOMING_BRANCH: ${{ env._USER_BR }}
+          GO_RELEASE_BRANCH: 'release'
+          # if test code has auth issues pass in another token:
+          # GITHUB_TOKEN: ${{ secrets.READ_PR_GITOPS_AUTOMATION }}
+          # try the github provided token
+          token: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          repo="${_GO_REPO}"
+          branch="release"
+          tag="${{ env.TAG_PHASE_2 }}"
+          start_time=$(date +%s)
+
+          # Get the commit SHA of the head of the release branch
+          branch_sha=$(curl -s -H "Authorization: token ${token}" \
+            "https://api.github.com/repos/${{ env._GO_REPO }}/git/refs/heads/$branch" | jq -r '.object.sha')
+          while true; do
+
+            # Get the list of tags in the repository
+            tag_sha=$(curl -s -H "Authorization: token ${token}" \
+              "https://api.github.com/repos/${{ env._GO_REPO }}/git/refs/tags/$tag" | jq -r '.object.sha')
+
+            # Compare the commit SHA of the tag and the release branch
+            if [ "$branch_sha" = "$tag_sha" ]; then
+              echo "[INFO] Asserted RC Tag was pushed on the Release Branch"
+              echo PR_RELEASE_TIMESTAMP=$(date +%s) >> $GITHUB_ENV
+              break
+            else
+              current_time=$(date +%s)
+              elapsed_time=$(($current_time - $start_time))
+
+              if [ $elapsed_time -ge 20 ]; then
+                echo "[Assertion Error] RC Tag was not pushed on the Release Branch"
+                echo "Exiting with error..."
+                exit 1
+              fi
+            fi
+
+            # Sleep for 3.5 seconds
+            sleep 3.5
+          done
+
+      # later we can assert whether the tag was a DEV Release or a PROD Release
+      
+
+      # THEN Assert that exatly one PR to main closed, with code merge, after PR_RELEASE_TIMESTAMP
+      - name: Assert that the PR to main closed with code merge
+        env:
+          GO_INCOMING_BRANCH: ${{ env._USER_BR }}
+          GO_MAIN_BRANCH: 'main'
+          # if test code has auth issues pass in another token:
+          # GITHUB_TOKEN: ${{ secrets.READ_PR_GITOPS_AUTOMATION }}
+          # try the github provided token
+          token: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          repo="${_GO_REPO}"
+          branch="main"
+          start_time=$(date +%s)
+
+          # Get the commit SHA of the head of the main branch
+          branch_sha=$(curl -s -H "Authorization: token ${token}" \
+            "https://api.github.com/repos/${_GO_OWNER}/${_GO_REPO_NAME}/git/refs/heads/$branch" | jq -r '.object.sha')
+
+          while true; do
+            
+              # Get the list of PRs in the repository
+              # invariant of ?head=boromir:release, since we accept only later than PR_RELEASE_TIMESTAMP
+              prs=$(curl -s -H "Authorization: token ${token}" \
+                "https://api.github.com/repos/${_GO_OWNER}/${_GO_REPO_NAME}/pulls?state=closed?base=main" | jq -r '.[] | select(.merged_at != null) | select(.merged_at >= env.PR_RELEASE_TIMESTAMP) | .head.sha')
+  
+              # assert this list of hashes has length of 1
+
+              if [ $(echo "$prs" | wc -l) -eq 1 ]; then
+                pr_sha=$(echo "$prs" | head -n 1)
+                if [ "$branch_sha" = "$pr_sha" ]; then
+                  echo "[INFO] Asserted PR to main closed with code merge"
+                  break
+                fi
+              # Compare the commit SHA of the PR and the main branch
+
+              else
+                current_time=$(date +%s)
+                elapsed_time=$(($current_time - $start_time))
+  
+                if [ $elapsed_time -ge 12 ]; then
+                  echo "[Assertion Error] PR to main did not close with code merge"
+                  echo "Exiting with error..."
+                  exit 1
+                fi
+              fi
+  
+              # Sleep for 3.5 seconds
+              sleep 3.5
+            done
+
+      # later we can assert that Main Br got PROD tag (v1.0.0, v1.2.0-dev, etc)
+      # and that Github Release was also made from that tag
