feat: allow automatic assertion of pushed to tag to retry, if tag not found on 1st try

diff --git a/.github/workflows/test_release_me_gitops_phase_1.yml b/.github/workflows/test_release_me_gitops_phase_1.yml
--- a/.github/workflows/test_release_me_gitops_phase_1.yml
+++ b/.github/workflows/test_release_me_gitops_phase_1.yml
@@ -328,32 +328,30 @@ jobs:
         # We verify the diff between the Expected Prod tag and main head is empty
         working-directory: ${{ env._GO_DIR }}
         run: |
-          git fetch
           git checkout main
           git pull origin main
           start_time=$(date +%s)
 
-          diffs=$(git diff --name-only "${{ env.EXPECTED_PROD_TAG }}" "${{ env.MAIN_BR }}")
-
           while true; do
-            if [ -z "$diffs" ]; then
+            git fetch --tags
+            diffs=$(git diff --name-only "${{ env.EXPECTED_PROD_TAG }}" "${{ env.MAIN_BR }}") || exit_code=$?
+
+            if [ $exit_code -eq 0 ] && [ -z "$diffs" ]; then
               echo "[INFO] Asserted PROD Tag '${{ env.EXPECTED_PROD_TAG }}' was pointed to same commit as head of ${{ env.MAIN_BR }} Branch"
               break
-            else
-              current_time=$(date +%s)
-              elapsed_time=$(($current_time - $start_time))
-
-              if [ $elapsed_time -ge ${{ env.TIMEOUT_LIMIT }} ]; then
-                echo "[Assertion Error] PROD Tag was not pushed on the ${{ env.MAIN_BR }} Branch"
-                echo "Exiting with error..."
-                exit 1
-              fi
             fi
 
-            # Sleep for ${{ env.POLL_FREQUENCY }} seconds
+            current_time=$(date +%s)
+            elapsed_time=$(($current_time - $start_time))
+
+            if [ $elapsed_time -ge ${{ env.TIMEOUT_LIMIT }} ]; then
+              echo "[Assertion Error] PROD Tag was not pushed on the ${{ env.MAIN_BR }} Branch"
+              echo "Exiting with error..."
+              exit 1
+            fi
+
+            echo "[INFO] Tag '${{ env.EXPECTED_PROD_TAG }}' not found yet. Retrying after sleeping ${{ env.POLL_FREQUENCY }} seconds..."
             sleep ${{ env.POLL_FREQUENCY }}
-            git fetch
-            diffs=$(git diff --name-only "${{ env.EXPECTED_PROD_TAG }}" "${{ env.MAIN_BR }}")
           done
 
       # in the future we may assert that Github Release was also made from that tag (which is now on main branch)
